In [220]:
import pandas as pd
import keras
from keras.layers import Dense
from keras.models import Sequential
import matplotlib.pyplot as plt
from keras.optimizers import SGD
import numpy as np
import tensorflow as tf


In [38]:
da = pd.read_csv('/content/diabetes.csv')

In [50]:
da.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [51]:
da.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [52]:
da.iloc[1].head(10)

Pregnancies                  1.000
Glucose                     85.000
BloodPressure               66.000
SkinThickness               29.000
Insulin                      0.000
BMI                         26.600
DiabetesPedigreeFunction     0.351
Age                         31.000
Outcome                      0.000
Name: 1, dtype: float64

In [53]:
da.axes

[RangeIndex(start=0, stop=768, step=1),
 Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
        'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
       dtype='object')]

In [54]:
da_c = da.copy()

In [ ]:
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
        'BMI', 'DiabetesPedigreeFunction', 'Age']

In [60]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(da.drop('Outcome',axis=1))
scaled = sc.transform(da.drop('Outcome',axis=1))

In [61]:
scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [62]:
from sklearn.model_selection import train_test_split

x = scaled
y = da['Outcome']

In [64]:
x.shape

(768, 8)

In [65]:
y.shape

(768,)

In [191]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 40)

In [192]:
x_train.shape

(537, 8)

In [193]:
y_train.shape

(537,)

In [303]:
model = Sequential()
model.add(Dense(64, activation = "relu"))
model.add(Dense(1, activation = "softmax"))
model.build(x_train.shape)
model.summary()

Model: "sequential_36"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_69 (Dense)            (537, 64)                 576       
                                                                 
 dense_70 (Dense)            (537, 1)                  65        
                                                                 
Total params: 641
Trainable params: 641
Non-trainable params: 0
_________________________________________________________________


In [304]:
from keras.optimizers.optimizer_v1 import Adam
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), loss="MeanSquaredError", metrics=['accuracy'])

In [305]:
x_train

array([[ 0.3429808 ,  0.47275805,  0.77001375, ...,  0.38169971,
        -0.56136849,  0.14967911],
       [-0.25095213,  2.06891246,  0.04624525, ...,  0.55938666,
        -0.19291401,  0.23476686],
       [-0.84488505,  1.88112959,  0.45982725, ...,  1.01629594,
         2.37418686, -0.95646168],
       ...,
       [ 1.82781311, -0.184482  , -3.57259724, ...,  0.41977549,
        -1.02042653, -0.36084741],
       [ 0.3429808 , -0.27837344, -0.16054575, ...,  0.7370736 ,
        -0.63687146,  0.66020563],
       [-0.84488505,  0.03459802, -0.26394125, ...,  0.39439164,
         0.66479969, -0.27575966]])

In [306]:
y_train.shape

(537,)

In [307]:
history = model.fit(x_train, y_train, batch_size = 14, epochs = 50)

Epoch 1/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 2/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 3/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 4/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 5/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 6/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 7/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 8/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 9/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 10/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.3333
Epoch 11/50
39/39 [

In [308]:
pred = model.predict(x_test)

8/8 [==============================] - 0s 2ms/step


In [309]:
pred

array([[0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.999

In [287]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, pred))
print(accuracy_score(y_test, pred))

ValueError: ignored

In [263]:
pred.shape

(231, 10)